pipeline {
  agent { label 'worker' }

  environment {
    REPO_URL = 'https://github.com/Charizmatik/node_js.git'
    REPO_BRANCH = 'master'
    IMAGE_NAME = 'node_js'
  }

  stages {
    stage('Pull the code') {
      steps {
        git branch: env.REPO_BRANCH, url: env.REPO_URL
      }
    }

    stage('Build Docker image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
          sh '''
            docker build \
              -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER} \
              -t ${DOCKERHUB_USER}/${IMAGE_NAME}:latest \
              .
          '''
        }
      }
    }

    stage('Run tests in Docker') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
          script {
            try {
              sh 'docker run --rm ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER} test'
            } catch (err) {
              echo 'Tests failed'
              throw err
            }
          }
        }
      }
    }

    stage('Push image to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
          sh '''
            echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
            docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
            docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:latest
          '''
        }
      }
    }
  }
}
